### ISSUE TITLE
alttp sm crossover site not working for me. help?

### ISSUE THREAD

**Issue by MegGriffin42** [tewtal/alttp_sm_combo_randomizer#115]
The crossover site is not working for me. And before you ask, yes I have cookies allowed and I have noscript set to allow all. Every time I try to generate a rando game, the site blanks out, leaving only the generate game and help options. Help?

**Comment by MegGriffin42** [comment]
Can somebody PLEASE answer my question, God fucking dammit!!! What the fuck is wrong with this shitty fucking combo randomizer site not fucking working for me?! I fucking tried everything under the fucking sun to get this fucktarded website working and zilch! Please answer or so help me, I WILL report this site to the better business bureau!

**Comment by tcprescott** [comment]
Before we address the actual issue you might be having, you should understand that support here is best effort.  You're not entitled to an answer to any question in a GitHub issue.  Also, the BBB would have nothing to do with a website on the internet that isn't selling anything.

That being said, have you tried using a different browser?  Also, try making sure your browser cache and the site local storage was cleared.  Here are some instructions: https://superuser.com/questions/519628/clear-html5-local-storage-on-a-specific-page/519642

**Comment by tewtal** [comment]
Please keep a civil tone here if you want to get help instead of this issue removed.
Are you still having issues with generating seeds? There was some downtime on the website a few days ago that's been fixed now.

If you're still having issues, I'd suggest looking at the link above and clear browser local storage and see if that helps. Using incognito mode without any extensions might help as well.

I'm closing this ticket for now, and if you're still having problems after trying the suggested methods here you can open a new issue with as much details as possible.
