### ISSUE TITLE
Spoiler not agreeing with what's in game?

### ISSUE THREAD

**Issue by Mathradi** [tewtal/alttp_sm_combo_randomizer#123]
Console or Emulator:  Snes9X v 1.56.2

Original Filename:  SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_366368579.sfc

Seed:  366368579 

Item, Entrance or Custom:  Other

Mode: open
Logic: 
ALTTP Logic: alttp-no-glitches-v10.2
SM Logic: sm-normal
Goal:  Defeat Ganon and Mother Brain
Difficulty:   Normal
Variation:   combo

Description of problem:
Spoiler not agreeing with what's in rom?  Most treasures are the same, but some key ones are not.  For example Magic Mirror not where it said it would be, got 50 rupees instead.  Instead of the Ice Rod Cave having the flute it is in Mini Muldorm Cave, near where the Magic Mirror was supposed to be?  I never did find the Magic Mirror, got very stuck very quickly.  Not a big deal, I can generate another one and try again.  

Just thought I should report this since it seems like the spoiler file logic is not quite synced with the logic that the game is using.

Spoiler (if available):
[SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_366368579.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3175398/SMALttP.-.sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_366368579.txt)

**Comment by Dimensional** [comment]
I'm having the same issue. Using seed 116283303, there was suppose to be a Moonstone in the Kakariko Well - Top, but instead I got a Missile Container. And I'm unable to bomb the back wall to    check that last chest, because at this stage of the game, the start of it all or Sphere 1, I don't have any bombs.

Spoiler Warning:
[SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_116283303.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3311082/SMALttP.-.sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_116283303.txt)

**Comment by drb647** [comment]
@Dimensional 
Kakariko Well - Top is the chest behind the bomb wall.  The logic assumes access to bombs at all times - check tree pulls, item dropping bugs hiding under bushes, kill some stuff - if all else fails, buy 'em.
