### ISSUE TITLE
Free wave beam after Mother Brain

### ISSUE THREAD

**Issue by drb647** [tewtal/alttp_sm_combo_randomizer#126]
Console or Emulator: snes9x 1.57
Seed: N/A
Mode: Standard
Logic: Normal
Goal: Ganon/Mother Brain
Difficulty: Normal
Variation: N/A

Description of problem:

Took an odd route through a seed today, ended up beating Mother Brain first with only Charge and Plasma beams.  Portaled out to LTTP but had to return to SM, when I did Hyper Beam was gone (expected) and Samus was firing Charge Plasma *and Wave*.  Inventory still shows only Charge and Plasma, removing both results in normal Wave Beam fire.  I'm guessing inventory isn't checked and Wave is assumed when removing Hyper; not a big deal at all but figured I would mention.

**Comment by drb647** [comment]
Update: same condition applies to Plasma Beam.  Beat MB with only Charge/Ice, portal out to LTTP and back, Samus fires Wave and Plasma when neither are in inventory.  Selecting Spazer on the inventory screen will remove the free Plasma beam (and not a cause Spazer/Plasma crash).

**Comment by JordanB500** [comment]
Hi my Computer crashed and i cant use it atm so i was wondering if you could maybe generate some spoilers for me using the same seed and send it to me id appreciate it, btw this is my second computer very slow and all that but now that my console emulator has a save file for smalttp i can continue where i left off im in turtle rock tryin to get the chests and i got the boss key this time and have made it to the long room with chests and eye lasers and without the mirror shield, blue mail or a serious amount of hearts i dont think i can get to them cuz i take 3-4 hearts in a single hit and im at 7 hearts so there isnt much i can do atm i cleared as much as possible of the dark palace and blind's hideout due to the red guys that copy your movements and due to red eyegores as well also when i got the speed boost i was curious as to how you get thru the wall leading to brinstar from crateria? there isnt enough room to do it and none of my abilities would work except maybe the power bombs which i cant use since i need the morph ball
    On Wednesday, June 5, 2019, 11:44:36 AM CDT, drb647 <notifications@github.com> wrote:  
 
 
Update: same condition applies to Plasma Beam. Beat MB with only Charge/Ice, portal out to LTTP and back, Samus fires Wave and Plasma when neither are in inventory. Selecting Spazer on the inventory screen will remove the free Plasma beam (and not a cause Spazer/Plasma crash).

**Comment by tewtal** [comment]
This is actually standard SM behaviour where the getting Hyper beam will set some weapons equipped even when they are not collected. There's no plans to change this either at the moment.
