### ISSUE TITLE
Casual Metroid seed not very casual...

### ISSUE THREAD

**Issue by obob912** [tewtal/alttp_sm_combo_randomizer#18]
Console or Emulator:

SNES-9x-1.55

Original Filename:

Seed:  738614059

Item, Entrance or Custom: 

Mode: open
Logic: alttp-no-glitches-v9.1
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem:  Loving the randomizer so far!  In this seed, the "playthrough" spoiler showed that the Mirror was in the missile below ice beam.  You have speed booster at this point, but not power bombs; my best guess is that the logic doesn't know that you need power bombs in order to go down from the speed booster/mockball room right of ice beam.  I was barely able to get the mirror by using a super missile to go the wrong way through a blue gate to get to crocomire, and then by charging a shinespark in crocomire's room and shinesparking left from the room above crocomire (I had space jump to get back up through the doorway in time; I imagine high jump would work too).  Power bombs and wave beam were all stuck after the mirror.

Anyways maybe I'm an idiot and missed something obvious, but there didn't seem to be any non-glitch way to get to the missile below ice beam without having either power bomb/wave beam, and even with wave beam it was a pretty crazy trick to pull off the shinespark from crocomire's room.

This was also a really interesting seed since power bombs were hidden so deep--in all the other seeds I've played you get power bombs super early and bombs late, and I really like it when there is better progression like this.  Looking forward to a seed where super missiles are similarly "gated," assuming that can happen.

Again, what an awesome idea for a hack, and thanks for your work on this!

Spoiler (if available):
[MetroidZeldaSpoiler4.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2045866/MetroidZeldaSpoiler4.txt)

**Comment by Josephur** [comment]
I would also like the latern to be added as vanilla in casual mode, if your not a great player then the dark rooms which may be holding a key item can be a real pain in the ... 🗡

**Comment by miketrethewey** [comment]
Except that Dark Room Navigation is never required. You’ll always have Lamp available *somewhere* before you need it.
Super Metroid’s Casual Logic does, at this time, require walljumps, shinesparks and Infinite Bomb Jumps and those are not likely to change to be more relaxed.

**Comment by Josephur** [comment]
Regardless it would be a nice casual mode option to not have to look all over for the lantern :)
I'm a huge fan of options.

**Comment by SoraHjort** [comment]
> Super Metroid’s Casual Logic does, at this time, require walljumps, shinesparks and Infinite Bomb Jumps and those are not likely to change to be more relaxed.

However, an option to not have those requirements would be beneficial. Not everyone is good with walljumps or bomb jumps. There are plenty of people out there that want to play, but have a hard time due to those hurdles.

[As DeceasedCrab suggested on twitter](https://twitter.com/DeceasedCrab/status/1011362337331318786), maybe have items that require those tricks be non-consequential items, like rupees or missile tanks. Alternatively, maybe a option so that progression items are where progression items are. So things would be in places such as Big Chests and Chozo statue rooms, and the like.

I know Tewtal had worked on a branch of the Super Metroid randomizer that separated items into groups. Maybe it's time to implement it into a true casual mode?

**Comment by miketrethewey** [comment]
The ALttPR framework does not natively support this method. New code would have to be written for it. Alternatively, a new logic level could be written that has an effective level that is lower than the current Casual that would have a design requiring more mobility inventory to facilitate access to some of the more-complicated locations that require tricky walljumps or IBJs.

**Comment by SoraHjort** [comment]
Right, I figured it was gonna require quite a bit of reworking. But it is something worth considering, whether it's new logic or replacing old code. On a side note, I think having the current casual difficulty named that is misleading. If new logic is implemented, I recommend calling current casual "Normal" and the lower difficulty take the name of "Casual"

Personally, I have no problem with many of the simple tricks. Mockball, Shinespark, Walljump (if using keyboard). Heck, first time I played through the crossover randomizer, I ended up learning Mockball, as well as having limited success with the gate glitch. But some friends, and even people I see online have problem with those, especially Walljump. And it would be nice to have a option of play for them.

**Comment by Julius187** [comment]
https://smalttp.speedga.me/h/NJMakz9y0K

Here's a seed I was playing earlier also with casual SM logic where I was required to clear lower norfair without space jump in order to get to the moon pearl at Ridley. IMO forcing lava dive and wall jumping up that shaft in lower norfair is a bit much for casual.

**Comment by sloanr333** [comment]
Julius, if you have the spoiler please post that instead

**Comment by Julius187** [comment]
Hope I did this correctly

[SMALttP - sm-casual_alttp-no-glitches-v9.2_normal-open_swords-randomized_morph-randomized_ganon_combo_530046455.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2189854/SMALttP.-.sm-casual_alttp-no-glitches-v9.2_normal-open_swords-randomized_morph-randomized_ganon_combo_530046455.txt)

**Comment by sloanr333** [comment]
You did perfectly. If I recall correctly, you can get to Ridley one of three ways in combomizer. Lava dive and turn left; you'll need space jump to get past the statue. Lava dive and turn right. You don't NEED space jump, but lava diving without it is rough. Finally, you can take the Mire right shed and it'll portal you to the right side of Golden Torizo. You had access to: Flippers and therefore Flute, Lamp => Hookshot => Titan's Mitts, Morph Bombs, High Jump Boots by then. I think what the seed wanted you to do was use that portal and make your way up the yellow pirate rooms. There are a number of ways to do that, but the easiest is infinite bomb jumps.

I guess there's a case to be made about IBJ not being a completely "casual" trick, but it can be learned by simply turning the game on and watching the intro demos.

If it makes you feel any better the East Lower Norfair logic is getting a rework for v10, though from what I can tell it won't make it any easier; but instead opens the area up if you have High Jump or Speed Booster instead of just IBJs. I mean it's more complicated than that but that's what I get out of it. I translated some of the logic to something a tad more human readable; take a look. There might be mistakes.

[v9.2 Lower Norfair East.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2190463/v9.2.Lower.Norfair.East.txt)
[v10 Lower Norfair East.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2190464/v10.Lower.Norfair.East.txt)
