### ISSUE TITLE
Inaccessable progression items

### ISSUE THREAD

**Issue by Lharm9** [tewtal/alttp_sm_combo_randomizer#37]
Console or Emulator: bsnes classic

 If emulator state which emulator and version. 

Original Filename: SMALttP - sm-casual_alttp-no-glitches-v9.2_normal-open_swords-randomized_morph-randomized_ganon_combo_310652793.sfc

Seed: 310652793

Item, Entrance or Custom:  Item

Mode: open
Logic: No Glitches/Casual
Goal: Defeat Ganon & MB
Difficulty: Normal
Variation: ALLTP+SM Combo Randomizer

Description of problem:  Book of Mudora is required for casual play as the seed as Varia Suit is on Ether Tablet.  Book is located in Crateria Super Missile location requiring Super Bombs for entry, Speed Booster and Ice beam.  Ice Beam is dug up from flute location, and the shovel is in Ganon's Tower.

Spoiler (if available):

**Comment by miketrethewey** [comment]
1. Right out of the gate
   * Saha's Hut: Sword (First sword) (need Link's Bombs)
   * Kak Well: Super Missile (Red/Green Doors)
   * Blind's Hideout: Lamp, Space
   * Aginah: Speed Booster (needs Link's Bombs)
   * Sunken Treasure: Moon Pearl
   * Mini-Moldorm Cave: Power Bomb (needs Link's Bombs)
   * Sanctuary: ETank

2. After first round of gear
   * ETank, Brinstar Ceiling: Progressive Glove (First glove) (needs Shinespark)
   * ETank (Hi-Jump Boots): Morph Ball (use Death Mountain Cave portal to Norfair since Link has Glove/Lamp)
   * Super Missile (Crateria): Book
      * Needs Power Bombs to access room
      * Can use Power Bombs to defeat enemies in room
      * Needs Shinespark to ascend
         * Generate it
         * Save it
         * Jump over pillars
         * Execute vertical Shinespark
   * Defeat Kraid
   * Varia Suit: Sword (Second sword)
   * Defeat Phantoon
   * Missile (outside Wrecked Ship top): Mirror
3. After second round of gear
   * Ether: Varia (using Book and two Swords)

**Comment by Lharm9** [comment]
> Super Missile (Crateria): Book
> 
>     Needs Power Bombs to access room
>     Can use Power Bombs to defeat enemies in room
>     Needs Shinespark to ascend
>         Generate it
>         Save it
>         Jump over pillars
>         Execute vertical Shinespark 

Oh, I attempted this.  Over and over. Somewhere in the neighborhood of 50 times.  The distance from where you save the shine spark before the pillars and where you jump is quite far - about a good 2 screens.  And while I'm sure it's possible, the difficulty level for executing this is really high.  Therefore, I don't know if I'd classify this maneuver as something that would make sense when you select Casual for your SM run.

**Comment by SmolBig** [comment]
It is a bit of a pain in the ass, tbh. Changing the reqs for that room (in casual) seems sensible to me.

**Comment by OmnerG** [comment]
I agree with SmolBig - for casual, the logic should requite ice beam for this room. I tried around 80 times to no avail, and filed it here as Issue #50  - then looked over the issues to find this one, which is essentially the same thing. It might be feasible with ice beam but no plasma - tricky angled-shot blasts quick enough to still get enough charge - but for casual, both should be in the logic.

**Comment by tewtal** [comment]
This does not require either ice or short charging. What you need to do is start as close to the possible to the Boyon's (yellow blobs) and run left and then charge a spark. After doing so just run back to the right and jump over them while being blue from the speed charge and then spark up.
