### ISSUE TITLE
Potential bug in V10 normal - HBJ required in this seed

### ISSUE THREAD

**Issue by SamuelTempus** [tewtal/alttp_sm_combo_randomizer#63]
Console or Emulator:
SNES9x 1.55 for Windows
 If emulator state which emulator and version.

Original Filename:

Seed: 306740259

Item, Entrance or Custom: Hookshot

Mode: open 
Logic: normal

Description of problem: 

I believe the normal (previously casual) logic is bugged to include horizontal bomb jumping to enter Wrecked Ship.  Hookshot is required to continue this seed, but is in the underwater missile location outside of Wrecked Ship.  At this point in the seed it is only obtainable via horizontal bomb jumps.  Gravity Suit, Speed Booster, Grappling Beam and Space Jump are only obtainable in this seed after getting Hookshot / other items that Hookshot makes obtainable. 

Spoiler (if available):

[SMALttP - sm-normal_alttp-no-glitches-v10_normal-open_swords-randomized_morph-randomized_ganon_combo_306740259.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2259098/SMALttP.-.sm-normal_alttp-no-glitches-v10_normal-open_swords-randomized_morph-randomized_ganon_combo_306740259.txt)

**Comment by CapnCrinklepants** [comment]
For reference, here's a breakdown of the logic as it currently is:

```
Crateria/East
	Can Enter (relevant portion):
		(
			$items->canUsePowerBombs() &
			$items->has('Super')
		)
	Missile (outside WS Bottom):
		(
			$items->has('SpeedBooster')
			| $items->has('Grapple')
			| $items->has('SpaceJump')
			| $items->canSpringBallJump()
			| $items->canAccessMaridiaPortal()
		)
```

So the logic definitely isn't expecting Horizontal Bomb Jumps here; instead it looks like it's allowing it because it expects you to use spring ball. It isn't obvious and doesn't really fit in with the old name- casual- but it should be easy enough to run through the door, full-height jump to the platform in the middle, and morph while holding jump and forward. When you land, you'll jump immediately and the spring ball will carry you over to the other side.

https://www.youtube.com/watch?v=ovq5MIX5pQ0

**Comment by SamuelTempus** [comment]
Thanks.  I knew this would be a relatively niche scenario, but had never heard or seen anyone using a spring ball jump to cross the moat.  Now I know a new trick.
